// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt76zRdJthIhc3alk8FqPRlU5uL-wpmV0',
    appId: '1:320247655568:web:07243b0c9ccf3aeee5bc15',
    messagingSenderId: '320247655568',
    projectId: 'laptopharbor01-256fb',
    authDomain: 'laptopharbor01-256fb.firebaseapp.com',
    storageBucket: 'laptopharbor01-256fb.firebasestorage.app',
    measurementId: 'G-MEQPCX78VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIGHhCCF5IzLAThDztgLwYKMFFW9_Iis',
    appId: '1:320247655568:android:193cc0549f657d98e5bc15',
    messagingSenderId: '320247655568',
    projectId: 'laptopharbor01-256fb',
    storageBucket: 'laptopharbor01-256fb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt76zRdJthIhc3alk8FqPRlU5uL-wpmV0',
    appId: '1:320247655568:web:79db4df76a04b2f4e5bc15',
    messagingSenderId: '320247655568',
    projectId: 'laptopharbor01-256fb',
    authDomain: 'laptopharbor01-256fb.firebaseapp.com',
    storageBucket: 'laptopharbor01-256fb.firebasestorage.app',
    measurementId: 'G-L3LK6NV97M',
  );
}
